---
apiVersion: v1
kind: Service
metadata:
  name: galega-ms-payment
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: "galega-ms-payment-lb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"  # Load Balancer Interno
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"       # Network Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal" # (Opcional) Especifica que o LB é interno
  labels:
    name: galega-ms-payment
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 9090        # Porta que será exposta
      targetPort: 9090  # Porta no container que receberá o tráfego
  selector:
    app: galega-ms-payment # Label selector para encontrar os pods corretos

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: galega-ms-payment
spec:
  selector:
    matchLabels:
      app: galega-ms-payment
  replicas: 1
  template:
    metadata:
      labels:
        app: galega-ms-payment
    spec:
      containers:
        - name: galega-ms-payment
          image: 985353326468.dkr.ecr.us-east-1.amazonaws.com/galega-ms-payment-app:latest
          ports:
            - containerPort: 9090

          # Setting Enviornmental Variables
          envFrom:
            - configMapRef:
                name: galega-ms-payment-config