apiVersion: v1
kind: ConfigMap
metadata:
  name: mercadopago-credentials
data:
  access_key: "TEST-4517379499194350-070720-7a234218d8d1d7fe49f0b99f6e21902c-449901113"
  public_key: "TEST-568883f9-e2de-4072-9c4b-54d28066b653"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-config
data:
  aws_region: "us-east-1"
  aws_access_key: "dummyKey"
  aws_secret_key: "dummySecret"
  aws_sqs_queue_url: "http://teste.com"

