---
apiVersion: v1
kind: Service
metadata:
  name: galega-ms-payment
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"  # Load Balancer Interno
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"       # Network Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal" # (Opcional) Especifica que o LB é interno
  labels:
    name: galega-ms-payment
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 9090        # Porta que será exposta
      targetPort: 9090  # Porta no container que receberá o tráfego
  selector:
    app: galega-ms-payment # Label selector para encontrar os pods corretos

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: galega-ms-payment
spec:
  selector:
    matchLabels:
      app: galega-ms-payment
  replicas: 1
  template:
    metadata:
      labels:
        app: galega-ms-payment
    spec:
      containers:
        - name: galega-ms-payment
          image: 793862496606.dkr.ecr.us-east-1.amazonaws.com/tgalega-ms-payment:latest
          ports:
            - containerPort: 8080

          # Setting Enviornmental Variables
          env:
            # Setting Database host address from configMap
            - name: MERCADOPAGO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: mercadopago-credentials
                  key: access_key

            - name: MERCADOPAGO_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: mercadopago-credentials
                  key: public_key

            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: aws-config
                  key: aws_region

            - name: AWS_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: aws-config
                  key: aws_access_key

            - name: AWS_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: aws-config
                  key: aws_secret_key

            - name: AWS_SQS_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  name: aws-config
                  key: aws_sqs_queue_url

            - name: LOGGING_LEVEL_ORG_FLYWAYDB
              value: DEBUG