name: Deploy Infrastructure with Terraform

on:
  issues:
    types:
      - opened  # Executa apenas quando uma nova issue é aberta.

jobs:
  deploy-infrastructure:
    if: ${{ github.event.issue.title == 'Deploy Infrastructure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        working-directory: ./infra
        run: terraform init

      - name: Validate Terraform
        working-directory: ./infra
        run: terraform validate

      - name: Plan Terraform
        working-directory: ./infra
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        working-directory: ./infra
        run: terraform apply -auto-approve tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
